# Settings.yml
---
conf.py:
  project: Inside TYPO3 CMS
  copyright: 2000-2013
  version: 4.2.0
  release: 4.2.0
  intersphinx_mapping:
    t3cmsapi:
    - http://typo3.org/api/typo3cms/
    - null
    t3api:
    - http://docs.typo3.org/typo3cms/CoreApiReference/
    - null
    t3cgl:
    - http://docs.typo3.org/typo3cms/CodingGuidelinesReference/
    - null
    t3install:
    - http://docs.typo3.org/typo3cms/InstallationGuide/
    - null
    t3security:
    - http://docs.typo3.org/typo3cms/SecurityGuide/
    - null
    t3tsconfig:
    - http://docs.typo3.org/typo3cms/TSconfigReference/
    - null
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3
    github_branch: latest
...
